USE traveling;

INSERT INTO t_city(name,code,provinceCode) VALUES('黄山市','AH_HS','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('合肥市','AH_HF','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('芜湖市','AH_WH','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('安庆市','AH_AQ','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('马鞍山市','AH_MAS','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('六安市','AH_LA','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('宿州市','AH_SZ','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('滁州市','AH_CZ','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('蚌埠市','AH_BB','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('巢湖市','AH_CH','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('淮南市','AH_HN','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('宣城市','AH_XC','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('亳州市','AH_BZ','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('淮北市','AH_HB','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('铜陵市','AH_TL','AH');
INSERT INTO t_city(name,code,provinceCode) VALUES('池州市','AH_CZS','AH');

INSERT INTO t_city(name,code,provinceCode) VALUES('南京市','JS_NJ','JS');
INSERT INTO t_city(name,code,provinceCode) VALUES('无锡市','JS_WX','JS');
INSERT INTO t_city(name,code,provinceCode) VALUES('常州市','JS_CZ','JS');
INSERT INTO t_city(name,code,provinceCode) VALUES('徐州市','JS_XZ','JS');
INSERT INTO t_city(name,code,provinceCode) VALUES('苏州市','JS_SZ','JS');
INSERT INTO t_city(name,code,provinceCode) VALUES('南通市','JS_NT','JS');
INSERT INTO t_city(name,code,provinceCode) VALUES('连云港市','JS_LYG','JS');
INSERT INTO t_city(name,code,provinceCode) VALUES('淮安市','JS_HA','JS');
INSERT INTO t_city(name,code,provinceCode) VALUES('扬州市','JS_YZ','JS');
INSERT INTO t_city(name,code,provinceCode) VALUES('盐城市','JS_YC','JS');
INSERT INTO t_city(name,code,provinceCode) VALUES('镇江市','JS_ZJ','JS');
INSERT INTO t_city(name,code,provinceCode) VALUES('泰州市','JS_TZ','JS');
INSERT INTO t_city(name,code,provinceCode) VALUES('宿迁市','JS_SQ','JS');

INSERT INTO t_city(name,code,provinceCode) VALUES('杭州市','ZJ_HZ','ZJ');
INSERT INTO t_city(name,code,provinceCode) VALUES('宁波市','ZJ_LB','ZJ');
INSERT INTO t_city(name,code,provinceCode) VALUES('温州市','ZJ_WZ','ZJ');
INSERT INTO t_city(name,code,provinceCode) VALUES('嘉兴市','ZJ_JX','ZJ');
INSERT INTO t_city(name,code,provinceCode) VALUES('湖州市','ZJ_HZS','ZJ');
INSERT INTO t_city(name,code,provinceCode) VALUES('绍兴市','ZJ_ZX','ZJ');
INSERT INTO t_city(name,code,provinceCode) VALUES('金华市','ZJ_JH','ZJ');
INSERT INTO t_city(name,code,provinceCode) VALUES('衢州市','ZJ_QZ','ZJ');
INSERT INTO t_city(name,code,provinceCode) VALUES('舟山市','ZJ_ZS','ZJ');
INSERT INTO t_city(name,code,provinceCode) VALUES('台州市','ZJ_TZ','ZJ');
INSERT INTO t_city(name,code,provinceCode) VALUES('利水市','ZJ_LS','ZJ');

INSERT INTO t_city(name,code,provinceCode) VALUES('南昌市','JX_NC','JX');
INSERT INTO t_city(name,code,provinceCode) VALUES('九江市','JX_JJ','JX');
INSERT INTO t_city(name,code,provinceCode) VALUES('景德镇市','JX_JDZ','JX');
INSERT INTO t_city(name,code,provinceCode) VALUES('萍乡市','JX_PX','JX');
INSERT INTO t_city(name,code,provinceCode) VALUES('新余市','JX_XY','JX');
INSERT INTO t_city(name,code,provinceCode) VALUES('鹰潭市','JX_YT','JX');
INSERT INTO t_city(name,code,provinceCode) VALUES('赣州市','JX_GZ','JX');
INSERT INTO t_city(name,code,provinceCode) VALUES('宜春市','JX_YC','JX');
INSERT INTO t_city(name,code,provinceCode) VALUES('上饶市','JX_SR','JX');
INSERT INTO t_city(name,code,provinceCode) VALUES('吉安市','JX_JA','JX');
INSERT INTO t_city(name,code,provinceCode) VALUES('抚州市','JX_FZ','JX');
